-- Oracle 23ai knowledge-base template: managed hybrid vector index.
-- Use this when the corpus already lives inside Oracle and the embedding model
-- runs in-database. Hybrid indexes are simpler to operate, but less flexible than
-- the explicit chunk table in knowledge_base_manual.sql.

DEFINE INDB_MODEL = doc_model

CREATE TABLE kb_hybrid_documents (
  doc_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_key           VARCHAR2(256) NOT NULL,
  source_uri        VARCHAR2(2048) NOT NULL,
  title             VARCHAR2(512),
  doc_text          CLOB NOT NULL,
  metadata          JSON,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT kb_hybrid_doc_key_uk UNIQUE (doc_key),
  CONSTRAINT kb_hybrid_source_uri_uk UNIQUE (source_uri)
);

CREATE HYBRID VECTOR INDEX kb_hybrid_idx
ON kb_hybrid_documents (doc_text)
PARAMETERS ('MODEL &INDB_MODEL');

COMMENT ON TABLE kb_hybrid_documents IS
  'Managed text+vector corpus for DBMS_HYBRID_VECTOR.SEARCH examples.';

-- Example search: vector-only retrieval through the hybrid index.
-- SELECT JSON_SERIALIZE(
--          DBMS_HYBRID_VECTOR.SEARCH(
--            JSON('{"hybrid_index_name":"KB_HYBRID_IDX","vector":{"search_text":"wallet rotation alerting"},"return":{"topN":10}}')
--          ) PRETTY
--        )
-- FROM dual;

-- Example search: blend lexical constraints with semantic search.
-- SELECT JSON_SERIALIZE(
--          DBMS_HYBRID_VECTOR.SEARCH(
--            JSON('{"hybrid_index_name":"KB_HYBRID_IDX","vector":{"search_text":"wallet rotation alerting"},"text":{"contains":"wallet AND alert"},"return":{"topN":10}}')
--          ) PRETTY
--        )
-- FROM dual;

-- Notes:
-- 1. Oracle documents hybrid vector indexes as an Oracle Text + AI Vector Search feature.
-- 2. This path is best when you want managed indexing and JSON search output.
-- 3. If you need external embeddings, rich per-chunk metadata, or fine-grained refresh
--    control, prefer knowledge_base_manual.sql instead.
