-- Oracle 23ai knowledge-base template: explicit document/chunk store.
-- Inspired by Oracle AI Vector Search docs, oracle/langchain-oracle (UPL-1.0),
-- and Haystack preprocessing/retrieval patterns (Apache-2.0).
--
-- Run with SQLcl or SQL*Plus. Adjust the DEFINE values before execution.

DEFINE EMBED_DIM = 1024
DEFINE INDB_MODEL = doc_model
DEFINE DISTANCE_METRIC = COSINE
DEFINE TARGET_ACCURACY = 90

CREATE TABLE kb_documents (
  doc_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_key           VARCHAR2(256) NOT NULL,
  source_uri        VARCHAR2(2048) NOT NULL,
  title             VARCHAR2(512),
  mime_type         VARCHAR2(128),
  language_code     VARCHAR2(32),
  checksum_sha256   VARCHAR2(64),
  source_etag       VARCHAR2(128),
  source_blob       BLOB,
  extracted_text    CLOB,
  metadata          JSON,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  updated_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT kb_documents_doc_key_uk UNIQUE (doc_key),
  CONSTRAINT kb_documents_source_uri_uk UNIQUE (source_uri)
);

CREATE TABLE kb_ingest_runs (
  run_id            NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id            NUMBER NOT NULL REFERENCES kb_documents(doc_id) ON DELETE CASCADE,
  chunking_profile  VARCHAR2(128) NOT NULL,
  embedding_model   VARCHAR2(256) NOT NULL,
  embedding_mode    VARCHAR2(32) NOT NULL,
  status            VARCHAR2(32) NOT NULL,
  started_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  finished_at       TIMESTAMP WITH TIME ZONE,
  chunks_written    NUMBER DEFAULT 0 NOT NULL,
  error_message     VARCHAR2(4000)
);

CREATE TABLE kb_chunks (
  chunk_id          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  doc_id            NUMBER NOT NULL REFERENCES kb_documents(doc_id) ON DELETE CASCADE,
  chunk_ord         NUMBER NOT NULL,
  chunk_offset      NUMBER,
  chunk_length      NUMBER,
  token_count_est   NUMBER,
  section_path      VARCHAR2(1024),
  page_no           NUMBER,
  chunk_text        CLOB NOT NULL,
  embed_text        CLOB NOT NULL,
  embedding         VECTOR(&EMBED_DIM, FLOAT32) NOT NULL,
  metadata          JSON,
  created_at        TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT kb_chunks_doc_ord_uk UNIQUE (doc_id, chunk_ord)
);

CREATE INDEX kb_chunks_doc_ix ON kb_chunks (doc_id, chunk_ord);
CREATE INDEX kb_ingest_runs_doc_ix ON kb_ingest_runs (doc_id, started_at DESC);
CREATE INDEX kb_chunks_ctx_ix ON kb_chunks (chunk_text) INDEXTYPE IS CTXSYS.CONTEXT;

CREATE VECTOR INDEX kb_chunks_hnsw_ix
ON kb_chunks (embedding)
ORGANIZATION INMEMORY NEIGHBOR GRAPH
DISTANCE &DISTANCE_METRIC
WITH TARGET ACCURACY &TARGET_ACCURACY
PARAMETERS (type HNSW, neighbors 32, efconstruction 300);

COMMENT ON TABLE kb_documents IS
  'Canonical source documents for the knowledge base. Keep original metadata here.';
COMMENT ON TABLE kb_chunks IS
  'Chunk-level retrieval units. embed_text may include title or domain metadata for better recall.';
COMMENT ON COLUMN kb_chunks.embed_text IS
  'Text sent to the embedding model. Keep chunk_text clean for citation, enrich embed_text for retrieval.';

-- Example: insert a source document after extracting text from PDF/HTML/etc.
-- INSERT INTO kb_documents (
--   doc_key,
--   source_uri,
--   title,
--   mime_type,
--   language_code,
--   checksum_sha256,
--   extracted_text,
--   metadata
-- ) VALUES (
--   'oracle-wallet-guide',
--   'https://docs.example.com/oracle/wallet-guide',
--   'Oracle Wallet Guide',
--   'text/html',
--   'en',
--   '9cf1...',
--   :extracted_text,
--   JSON('{"product":"oracle","audience":"platform"}')
-- );

-- Example: rebuild chunks for a single document using an in-database embedding model.
--
-- The embed_text pattern mirrors Haystack's metadata-embedding approach: title and
-- high-signal metadata are injected into the embedding input, while chunk_text stays
-- citation-friendly and unchanged.
--
-- DELETE FROM kb_chunks WHERE doc_id = :doc_id;
--
-- INSERT INTO kb_chunks (
--   doc_id,
--   chunk_ord,
--   chunk_offset,
--   chunk_length,
--   token_count_est,
--   section_path,
--   page_no,
--   chunk_text,
--   embed_text,
--   embedding,
--   metadata
-- )
-- SELECT
--   d.doc_id,
--   ROW_NUMBER() OVER (ORDER BY c.chunk_offset, c.chunk_length, c.chunk_data) AS chunk_ord,
--   c.chunk_offset,
--   c.chunk_length,
--   CEIL(c.chunk_length / 4),
--   JSON_VALUE(d.metadata, '$.section_path' RETURNING VARCHAR2(1024)),
--   TO_NUMBER(JSON_VALUE(d.metadata, '$.page_no' RETURNING VARCHAR2(64) NULL ON ERROR)),
--   c.chunk_data AS chunk_text,
--   (
--     CASE WHEN d.title IS NOT NULL THEN 'title: ' || d.title || CHR(10) || CHR(10) ELSE '' END ||
--     CASE
--       WHEN JSON_VALUE(d.metadata, '$.source_type' RETURNING VARCHAR2(128)) IS NOT NULL
--       THEN 'source: ' || JSON_VALUE(d.metadata, '$.source_type' RETURNING VARCHAR2(128)) || CHR(10)
--       ELSE ''
--     END ||
--     c.chunk_data
--   ) AS embed_text,
--   VECTOR_EMBEDDING(
--     &INDB_MODEL USING (
--       CASE WHEN d.title IS NOT NULL THEN 'title: ' || d.title || CHR(10) || CHR(10) ELSE '' END ||
--       CASE
--         WHEN JSON_VALUE(d.metadata, '$.source_type' RETURNING VARCHAR2(128)) IS NOT NULL
--         THEN 'source: ' || JSON_VALUE(d.metadata, '$.source_type' RETURNING VARCHAR2(128)) || CHR(10)
--         ELSE ''
--       END ||
--       c.chunk_data
--     ) AS data
--   ) AS embedding,
--   JSON_OBJECT(
--     'source_uri' VALUE d.source_uri,
--     'title' VALUE d.title,
--     'chunk_offset' VALUE c.chunk_offset,
--     'chunk_length' VALUE c.chunk_length,
--     'doc_key' VALUE d.doc_key
--     RETURNING JSON
--   ) AS metadata
-- FROM kb_documents d,
--      VECTOR_CHUNKS(
--        d.extracted_text BY WORDS MAX 220 OVERLAP 30 SPLIT RECURSIVELY
--      ) c
-- WHERE d.doc_id = :doc_id;
--
-- INSERT INTO kb_ingest_runs (
--   doc_id,
--   chunking_profile,
--   embedding_model,
--   embedding_mode,
--   status,
--   finished_at,
--   chunks_written
-- )
-- SELECT :doc_id, 'words-220-overlap-30', '&INDB_MODEL', 'database', 'complete', SYSTIMESTAMP, COUNT(*)
-- FROM kb_chunks
-- WHERE doc_id = :doc_id;
--
-- COMMIT;

-- If you must call an external embedding provider instead of an in-database ONNX model,
-- keep the same schema and replace VECTOR_EMBEDDING(...) with DBMS_VECTOR_CHAIN.UTL_TO_EMBEDDING
-- or UTL_TO_EMBEDDINGS using your provider credentials.
